name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: docker login 
      run: docker login -u mariodmc -p 9c429198-ff71-48c7-8f9f-08c00c40dc51
    - name: Push the Docker image
      run: docker push mariodmc/sentimentapp:lastest
