name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d')"
    - name: docker login 
      run: docker login -u mariodmc -p ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mariodmc/sentimentapp:${{ steps.date.outputs.date }}
    - name: Push the Docker image
      run: docker push mariodmc/sentimentapp:${{ steps.date.outputs.date }}
    - name: Build the lastest Docker image
      run: docker build . --file Dockerfile --tag mariodmc/sentimentapp:lastest
    - name: Push the lastest Docker image
      run: docker push mariodmc/sentimentapp:lastest
